import type { Metadata } from 'next';
import './globals.scss';
import { geistMono, geistSans } from './fonts';
import Sidebar from '@/components/layout/Sidebar/Sidebar';
import { SIDEBAR_MENU } from '@/data/sidebarMenu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={'layout'}>
          <Sidebar menu={SIDEBAR_MENU} userName="Eldar Gezalov" />
          {children}
        </div>
      </body>
    </html>
  );
}
